//! Markdown specification export: turns the lifted structure and the
//! semantic annotations accumulated via `annotate` into a human-readable
//! specification document — the "spec recovery" output for legacy code.

use std::fmt::Write as _;

use anyhow::Result;
use specgraphen_model::{JavaEntityType, SemanticAnnotation, SpaceData};

pub fn spec_markdown(space_data: &SpaceData) -> Result<String> {
    let mut out = String::new();

    let annotated_count = space_data
        .annotations
        .values()
        .filter(|ann| has_content(ann))
        .count();
    writeln!(out, "# Specification: {}", space_data.space.name)?;
    writeln!(out)?;
    writeln!(
        out,
        "_Generated by specgraphen from static analysis and accumulated annotations. \
         {} entities, {} annotated. Every statement is backed by a source witness; \
         unannotated members are listed by signature only._",
        space_data.entities.len(),
        annotated_count
    )?;

    let mut classes: Vec<_> = space_data
        .entities
        .iter()
        .filter(|e| {
            matches!(
                e.entity_type,
                JavaEntityType::Class
                    | JavaEntityType::Interface
                    | JavaEntityType::Enum
                    | JavaEntityType::Record
            )
        })
        .collect();
    classes.sort_by(|a, b| a.fqn.cmp(&b.fqn));

    let mut current_package = String::new();

    for class in classes {
        let package = class.fqn.rsplit_once('.').map(|(p, _)| p).unwrap_or("");
        if package != current_package {
            writeln!(out)?;
            writeln!(out, "## Package `{package}`")?;
            current_package = package.to_string();
        }

        writeln!(out)?;
        writeln!(
            out,
            "### `{}` ({})",
            class.label,
            class.entity_type.cell_type_str()
        )?;
        writeln!(out, "_{}:{}_", class.witness.file, class.witness.start_line)?;
        if let Some(ann) = annotation_for(space_data, &class.cell_id) {
            write_annotation(&mut out, ann)?;
        }

        let prefix = format!("{}.", class.fqn);
        let mut members: Vec<_> = space_data
            .entities
            .iter()
            .filter(|e| {
                e.fqn.starts_with(&prefix)
                    && matches!(
                        e.entity_type,
                        JavaEntityType::Method | JavaEntityType::Constructor
                    )
            })
            .collect();
        members.sort_by_key(|e| e.witness.start_line);

        for member in members {
            writeln!(out)?;
            writeln!(
                out,
                "#### `{}` — {}:{}",
                member.label, member.witness.file, member.witness.start_line
            )?;
            match annotation_for(space_data, &member.cell_id) {
                Some(ann) => write_annotation(&mut out, ann)?,
                None => writeln!(out, "_(not yet annotated)_")?,
            }
        }
    }

    Ok(out)
}

fn annotation_for<'a>(space_data: &'a SpaceData, cell_id: &str) -> Option<&'a SemanticAnnotation> {
    space_data
        .annotations
        .get(cell_id)
        .filter(|ann| has_content(ann))
}

fn has_content(ann: &SemanticAnnotation) -> bool {
    ann.intent.is_some()
        || ann.behavior.is_some()
        || ann.error_behavior.is_some()
        || !ann.preconditions.is_empty()
        || !ann.postconditions.is_empty()
        || !ann.side_effects.is_empty()
        || !ann.invariants.is_empty()
}

fn write_annotation(out: &mut String, ann: &SemanticAnnotation) -> Result<()> {
    if let Some(ref intent) = ann.intent {
        writeln!(out, "- **Intent**: {intent}")?;
    }
    if let Some(ref behavior) = ann.behavior {
        writeln!(out, "- **Behavior**: {behavior}")?;
    }
    write_list(out, "Preconditions", &ann.preconditions)?;
    write_list(out, "Postconditions", &ann.postconditions)?;
    write_list(out, "Invariants", &ann.invariants)?;
    write_list(out, "Side effects", &ann.side_effects)?;
    if let Some(ref err) = ann.error_behavior {
        writeln!(out, "- **Error behavior**: {err}")?;
    }
    Ok(())
}

fn write_list(out: &mut String, title: &str, items: &[String]) -> Result<()> {
    if items.is_empty() {
        return Ok(());
    }
    writeln!(out, "- **{title}**:")?;
    for item in items {
        writeln!(out, "  - {item}")?;
    }
    Ok(())
}
